### ISSUE TITLE
Shadow DOM breaks CSS inherit

### ISSUE THREAD

**Issue by eric-starke** [languagetool-org/languagetool#10671]
I am using these rules in my stylesheet to inherit the `box-sizing` attribute from root:

```css
*,
*::before,
*::after {
  box-sizing: inherit;
}

:root {
  box-sizing: border-box;
}
```

When the user of my website has the LanguageTool extension installed, breaks this the inheritance for the elements that are inserted into a `<slot>` by the extension.
Is it possible to fix this on your side? I found a fix for this case, but there could be more unintended style changes regarding inherit.
