### ISSUE TITLE
RTL support on pageCheck

### ISSUE THREAD

**Issue by ebraminio** [languagetool-org/languagetool#152]
For RTL support for Persian on [this page for example](https://tools.wmflabs.org/languagetool/pageCheck/index?url=%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7%3A%D9%82%D9%87%D9%88%D9%87%E2%80%8C%D8%AE%D8%A7%D9%86%D9%87%2F%DA%AF%D9%88%D9%86%D8%A7%DA%AF%D9%88%D9%86&lang=fa), a separate [main.css](https://tools.wmflabs.org/languagetool/static/css/main.css) (e.g. main.rtl.css) should be used for RTL languages. One approach could be putting whole of main.css on [cssjanus](http://cssjanus.commoner.com/) (or [CSSJanus.php](https://www.mediawiki.org/wiki/Manual:CSSJanus.php)) and generating new one, this is mine main.rtl.css and it looks OK:

![rtl](https://cloud.githubusercontent.com/assets/833473/3971737/a99f2a4e-27d6-11e4-913d-bea0a9e0694b.png)

``` CSS
html { direction: rtl; } /* only not generated by CSSJanus rule 
  you should put a ltr one so in conversion it would be converted to RTL automatically
  or make it attribute for <html dir="rtl"> like mediawiki which is better */

html * {
    margin: 0;
    /*padding: 0; SELECT NOT DISPLAYED CORRECTLY IN FIREFOX */
}

/* GENERAL */

.spinner {
    padding: 5px;
    position: absolute;
    left: 0;
}

body {
    background: #fff;
    color: #000000;
    font: 12px verdana, arial, helvetica, sans-serif;
}

h1 {
    color: #006dba;
    font-weight: bold;
    font-size: 20px;
    margin: .8em 0 .3em 0;
}

h2 a:link, a:visited, a:hover {
    color: #67a918;
}

h2 {
    margin-top: 20px;
    margin-bottom: 4px;
    line-height: 20px;
}

.firstHeadline {
    margin-top: 8px;
    margin-bottom: 8px;
}

a:link, a:visited, a:hover {
    color: #678718;
    font-weight: bold;
    text-decoration: none;
}

a:hover {
    color: #000;
    font-weight: bold;
    text-decoration: none;
}

a:active {
    color: #666;
    font-weight: bold;
    text-decoration: none;
}

ul {
    padding-right: 15px;
}
input[type="button"] {
    background-color: #eeeeee;
}
input[type="submit"] {
    background-color: #eeeeee;
}

input, select {
    background-color: #fcfcfc;
    border: 1px solid #ccc;
    font: 12px verdana, arial, helvetica, sans-serif;
    margin: 2px 0;
    padding: 2px 2px;
}
select {
    padding: 2px 0 2px 2px;
}
textarea {
    background-color: #fcfcfc;
    border: 1px solid #ccc;
    font: 12px verdana, arial, helvetica, sans-serif;
    vertical-align: top;
    padding: 2px 2px;
}

input:focus, select:focus, textarea:focus {
    border: 1px solid #b2d1ff;
}

.body {
    float: right;
    margin: 0 15px 10px 15px;
}

/* MESSAGES AND ERRORS */

.message {
    background: #f3f8fc url(../images/skin/information.png) 8px 50% no-repeat;
    border: 1px solid #b2d1ff;
    color: #006dba;
    margin: 10px 0 5px 0;
    padding: 5px 30px 5px 5px
}

.warn {
    border: 1px solid #ae985d;
    color: #524c2e;
    background: #ffdf88;
    margin: 10px;
    padding: 5px;
}

div.errors {
    background: #fff3f3;
    border: 1px solid red;
    color: #cc0000;
    margin: 10px 0 5px 0;
    padding: 5px;
}
div.errors ul {
    list-style: none;
    padding: 0;
}
div.errors li {
    background: url(../images/skin/exclamation.png) 8px 100% no-repeat;
    line-height: 16px;
    padding-right: 30px;
}

li {
    line-height: 130%;
}

td.errors select {
    border: 1px solid red;
}
td.errors input {
    border: 1px solid red;
}

/* TABLES */

table {
    border: 1px solid #ccc;
    width: 100%
}
tr {
    border: 0;
}
td, th {
    font: 12px verdana, arial, helvetica, sans-serif;
    line-height: 12px;
    padding: 5px 6px;
    text-align: right;
    vertical-align: top;
}
th {
    background: #fff url(../images/skin/shadow.jpg);
    color: #666;
    font-size: 12px;
    font-weight: bold;
    line-height: 17px;
    padding: 2px 6px;
}
th a:link, th a:visited, th a:hover {
    color: #333;
    display: block;
    font-size: 10px;
    text-decoration: none;
    width: 100%;
}
th.asc a, th.desc a {
    background-position: left;
    background-repeat: no-repeat;
}
th.asc a {
    background-image: url(../images/skin/sorted_asc.gif);
}
th.desc a {
    background-image: url(../images/skin/sorted_desc.gif);
}

.odd {
    background: #f7f7f7;
}
.even {
    background: #fff;
}

/* LIST */

.list table {
    border-collapse: collapse;
}
.list th, .list td {
    border-right: 1px solid #ddd;
}

/* PAGINATION */

.paginateButtons {
    background: #fff url(../images/skin/shadow.jpg) bottom repeat-x;
    border: 1px solid #ccc;
    border-top: 0;
    color: #666;
    font-size: 10px;
    overflow: hidden;
    padding: 10px 3px;
}
.paginateButtons a {
    background: #fff;
    border: 1px solid #ccc;
    border-color: #ccc #ccc #aaa #aaa;
    color: #666;
    margin: 0 3px;
    padding: 2px 6px;
}
.paginateButtons span {
    padding: 2px 3px;
}

/* DIALOG */

.dialog {
    max-width: 800px;
}

.dialog table {
    padding: 5px 0;
}

.prop {
    padding: 5px;
}
.prop .name {
    text-align: right;
    width: 15%;
    white-space: nowrap;
}
.prop .value {
    text-align: right;
    width: 85%;
}

/* Added for ltcomunity */

/* features on the homepage */
.mainPart {
    margin-right: 15px;
}

.header {
    background: #87b220;
    padding-bottom: 15px;
}

.header a {
    color: white;
}

.logo {
    margin-top: 0;
    margin-right: 15px;
    margin-bottom: 8px;
}

.sublogo {
    margin-right: 15px;
    margin-bottom: 5px;
}

.login {
    margin-right: 15px;
}
.imprint {
    margin-top: 5px;
    margin-right: 15px;
}

.error {
    font-weight: bold;
    padding-right: 2px;
    padding-left: 2px;
    padding-bottom: 2px;
    background-image: url("../images/squiggle.png");
    background-repeat: repeat-x;
    background-position: right bottom;
}
.spellingError {
    font-weight: bold;
    padding-right: 2px;
    padding-left: 2px;
    padding-bottom: 2px;
    background-image: url("../images/squiggle_red.png");
    background-repeat: repeat-x;
    background-position: right bottom;
    vertical-align: text-top;
}

.exampleSentence {
    background-color: #eee;
}

.correction {
    background: #d7ffd7;
}

.additional {
    font-weight: normal !important;
    color: #999 !important;
}

.additionalFeedMatchLink {
    font-weight: normal !important;
    color: #666 !important;
}
.additionalFeedMatchLink:hover {
    font-weight: normal !important;
    background-color: #eeeeee;
}

.languageButton {
    padding: 5px;
    padding-right: 5px;
    padding-left: 5px;
    margin-right: 0;
    margin-left: 0;
    background: #94c324;
}

.languageButton a {
    color: black;
}

.languageButton a:hover {
    background-color: #9ed025;
}

.activelang {
    color: white;
    font-weight: bold;
}

.errorList {
    margin-bottom: 5px;
}


.pattern {
    font-family: monospace;
    font-size: larger;
}

/* link to LT homage */
.lthomepage {
    margin-top: 15px;
}

/* link list with all supported languages */
.langselection {
    line-height: 30px;
    margin-bottom: 15px;
}

.javaRule {
    color: #777777;
}

.metaInfo {
    color: #777777;
}

.sourceLink {
    font-weight: normal !important;
    color: #777777 !important;
}

.preFilledField {
    width: 400px;
    color: #999999;
}

.languageToolVersion {
    margin-top: 10px;
    color: #aaaaaa;
}

.filterMatch {
    background-color: yellow;
}

.ruleMessage {
    color: #333333;
    font-weight: bold;
    width: 60%
}

.ruleMessage .category {
    color: #999999;
    font-weight: normal;
}

.ruleXmlArea {
    padding: 5px;
    background-color: #f5f5f5;
}

.ruleXml {
    white-space: pre;
    font-family: monospace;
}

.xmlTag {
    color: #555555;
}

.wikiCheckTable {
    width: 1000px;
    padding: 0;
    margin-bottom: 15px;
    border-style: none;
}

.wikiCheckTable td {
    padding: 2px;
}

.textAnalysis {
}

.textAnalysis .disambiguatorLog {
    color: #333;
}
.textAnalysis .pos {
    color: #777;
}
.textAnalysis .chunk {
    color: #556270;
}
```
