### ISSUE TITLE
Self-hosted LT server not accessible with Firefox add-on

### ISSUE THREAD

**Issue by xthursdayx** [languagetool-org/languagetool#6513]
When trying to use my self-hosted LT server with the Firefox LT add-on, I get the following error from the LT pop-up: `Cannot connect to https://grammar.my.domain/v2/check - please check your internet connection or try again in a minute (#1, code=0)`. However, when I try using the LT extension in Chromium with the same self-hosted LT server I don't have any problems. I am trying this using a fresh install of Firefox with no additional extensions installed and only the standard browser security setting.

I am running the LT server using the [Erikvl87/docker-languagetool](https://github.com/Erikvl87/docker-languagetool) docker image reverse proxied using NGINX. The LT standalone server starts with the ` --public --allow-origin '*'` flags and I start my container using a docker-compose yml with the following settings:
```
services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
        - 8010:8010 
    environment:
        - langtool_languageModel=/ngrams
        - Java_Xms=512m
        - Java_Xmx=2818m
        - langtool_pipelinePrewarming=true
        - langtool_pipelineCaching=true
    volumes:
        - /home/xthursdayx/languagetool/ngrams:/ngrams
```

I have also tried starting the the LT standalone server with `--allow-origin "*"` instead of `--allow-origin '*'`, but it didn't make any difference. 

I can't figure out why this is working in Chromium but not Firefox after having spent most of the afternoon loading and reloading websites, reading the browser console log, and adding and removing NGINX headers. It seems like this issue might be related to one (or both) of these two questions on StackOverflow: https://stackoverflow.com/questions/40185123/error-content-security-policy-the-page-s-settings-blocked-the-loading-of-a-res and https://stackoverflow.com/questions/56386307/loading-of-a-resource-blocked-by-content-security-policy but I'm not sure. 

Any ideas how to troubleshoot this? Thanks!
