### ISSUE TITLE
Bouncing Icon on overlays

### ISSUE THREAD

**Issue by rezaffm** [languagetool-org/languagetool#8825]
Hi,

I am uncertain if it's intended or not, but if you working in an editor, for instance tinymce and once you save with an overlay over the editor, the icon of LanguageTool vanishes for a few ms.

I noticed that there is a wrapper-hide class applied when the DOM updates, and it seems like there is no chance to manually overwrite it (as it is with !important display: none).

Not the end of the world, but any chance to avoid it?

**Comment by rezaffm** [comment]
Okay, this kind of does the "trick"

```css
html:not([data-lt-script-installed]):not(.__lt-dummy-1):not(.__lt-dummy-2):not(.__lt-dummy-3):not(.__lt-dummy-4):not(.__lt-dummy-5):not(.__lt-dummy-6):not(.__lt-dummy-1685518151046) lt-toolbar .lt-toolbar__wrapper-hide.lt-toolbar__wrapper-hide.lt-toolbar__wrapper-hide {
    display: block !important;
}
```

I dont get to be frank, but it stops the bouncing on overlays.
